version: '3'
services:
  catalog-service:
    build: ./catalog-service
    ports:
      - "3000:3000"
    networks:
      - book_store_network
    volumes:
      - /catalog-service

  order-service:
    build: ./order-service
    ports:
      - "3001:3001"
    networks:
      - book_store_network
    depends_on:
      - catalog-service



networks:
  book_store_network:
    driver: bridge
